### ISSUE TITLE
No Linux or Windows setup for ManageIQ Dev Appliance?

### ISSUE THREAD

**Issue by mikebutak** [ManageIQ/manageiq-appliance-dev-setup#5]
Hello,

[This README file](https://github.com/ManageIQ/manageiq-appliance-dev-setup) provides a link to instructions on how to create the ManageIQ Appliance dev setup for a MAC OSX environment, but it says that Linux instructions are TBD.  See Screenshot:

![image](https://user-images.githubusercontent.com/34036100/79345279-c2db8b80-7ee5-11ea-983b-f8f4d01fb9cd.png)

Are we truly limited to MAC OS for development?  Are there no instructions out there for setting up in a Linux or Windows environment?  

Thank you!

**Comment by carbonin** [comment]
This is a specific way of setting up a VM to pull in your source from a directory on the VM host (your laptop). The standard developer setup documentation is https://github.com/ManageIQ/guides/blob/master/developer_setup.md

**Comment by agrare** [comment]
@mikebutak if you want to run an appliance on your linux laptop instead of the typical developer setup you can use Virtual Machine Manager to create a VM and point to any of the .qcow2 builds.

**Comment by mikebutak** [comment]
> @mikebutak if you want to run an appliance on your linux laptop instead of the typical developer setup you can use Virtual Machine Manager to create a VM and point to any of the .qcow2 builds.

Thanks @agrare and @carbonin.  Am I correctly understanding that the typical dev setup (referenced in your link, Nick) is not on a local workstation but in a vm?  Also, I see instructions for Fedora, CentOS, Debian, and Ubuntu.  If we use RHEL,

**Comment by agrare** [comment]
@mikebutak It's up to you but typically development is done on a local workstation.  Personally I've only loaded up full appliances if I'm testing something on an older version that I can't get to bundle install anymore.

There are mac instructions here because you can't install the VMware VDDK on a mac, so smartstate developers run an appliance to do smartstates on their laptops.
